import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home(props) {
  const [blogs, setblogs] = useState(props.allBlogs);

  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        {/* Bootstrap Css imported globally*/}
      </Head>
      {/* <Script src="script.js" strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting <a href="#">Coder</a>
        </h1>

        <div className="mt-5">
          {/* we cannot use Image of next.js while creating a static website */}
          <Image
            src="/blog.png"
            className="p-1"
            height={400}
            width={400}
          ></Image>

          {/* so while creating a static website we can use HTML's img tag */}
          {/* <img src="/blog.png" className="p-1" alt="Blog" height={400} width={400} /> */}
        </div>

        <p className={styles.description}>
          <i className="">A blog for hunting coders by a hunter coder</i>
        </p>

        <div className={styles.grid}>
          <h2 className={styles.popularBlogsHeading}>Latest Blogs</h2>

          {blogs.map((blogItem) => {
            return (
              <Link key={blogItem.slug} href={`/blogpost/${blogItem.slug}`}>
                <a className={`${styles.card}`}>
                  <div>
                    <h2>{blogItem.title}&rarr;</h2>
                  </div>
                  <div>
                    <p>{blogItem.metaDesc}.</p>
                  </div>
                </a>
              </Link>
            );
          })}
          {/* <a className={`${styles.card}`}>
            <h2>How to learn JavaScript in 2022?&rarr;</h2>
            <p>JavaScript is the language used to design logic for the web.</p>
          </a>

          <a className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a className={styles.card}>
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  let data = await fetch("http://localhost:3000/api/blogs");
  let allBlogs = await data.json();
  return {
    props: { allBlogs },
  };
}
